### PR TITLE
Sink availability check and adapter semantic matching added

### LINKED ISSUE #28: Empty K_SINK propagated to underlying Knative Service when sink isn't ready
I have a Function with the following sink configured:

```yaml
  sink:
    ref:
      apiVersion: targets.triggermesh.io/v1alpha1
      kind: SlackTarget
      name: chat-notifications
```

The sink is not ready yet:

```console
$ kubectl get slacktargets.targets.triggermesh.io
NAME                 URL   READY   REASON               AGE
chat-notifications         False   AdapterUnavailable   21m
```

However, the Function service is created immediately with an empty `K_SINK`, instead of waiting for the sink to become ready.

This causes unexpected behaviours because, instead of waiting for everything to be up, Triggers immediately fire events at the Function, which replies directly to the sender instead of shipping those events where they were supposed to be sent. As a result, the sender understands that everything went as expected, yet the final destination never received the payload.

It might be safer to report "NotReady" in the Function status if the sink's URL can't be determined, so that subscriptions pause the event flow.

### LINKED ISSUE #29: Check adapter reconciliation logic
In some cases, Function object update causes extra revisions (at least 2) to be created in adapter Ksvc. Need to figure out why is it happening and fix it if possible.

### PR DESCRIPTION
**Pull request by tzununbekov**
This PR should resolve #28 by setting Function's readiness status into `SinkUnavailable` if sink address cannot be resolved.
Also, it partially fixes  #29 by introducing `semantic` package for adapter ksvc matching needs.

### CODE REVIEW

File: pkg/reconciler/function/semantic/semantic.go [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+// Semantic can do semantic deep equality checks for Kubernetes API objects.
+//
+// For a given comparison function
+//
+//   comp(a, b interface{})
+//
+// 'a' should always be the desired state, and 'b' the current state for
+// DeepDerivative comparisons to work as expected.
+var Semantic = conversion.EqualitiesOrDie(
+	deploymentEqual,
```
Comment (antoineco) [inline pkg/reconciler/function/semantic/semantic.go:38]: `deploymentEqual` can probably be removed from this repo since it isn't used. I don't mind if you prefer to keep it though.

File: pkg/reconciler/function/semantic/semantic.go [hunk 2]
```diff
@@ -0,0 +1,131 @@
+/*
+Copyright (c) 2020 TriggerMesh Inc.
```
Comment (antoineco) [inline pkg/reconciler/function/semantic/semantic.go:2]: nit: 2021

File: pkg/reconciler/function/function.go [hunk 3]
```diff
@@ -102,8 +103,17 @@ func (r *Reconciler) ReconcileKind(ctx context.Context, o *functionv1alpha1.Func
 	}
 	o.Status.MarkConfigmapAvailable()
 
+	sink, err := r.resolveSink(ctx, o)
+	if err != nil {
+		logger.Error("Error resolving sink", zap.Error(err))
+		o.Status.MarkSinkUnavailable()
+		return err
+	}
```
Comment (antoineco) [inline pkg/reconciler/function/function.go:111]: This will cause a double logging of the same error, on every error:
* once here
* once after the call to the top-level `ReconcileKind()`, which bubbles up the error at line 110

Suggestion to avoid that: simply return the error wrapped with a short context string:

```suggestion
	sink, err := r.resolveSink(ctx, o)
	if err != nil {
		o.Status.MarkSinkUnavailable()
		return fmt.Errorf("resolving sink URI: %w", err)
	}
```

**Review by antoineco — APPROVED** [review]
Nice! Approving with nit picks.
